version: "3"
services:
  client:
    image: punss21/multi-client
    mem_limit: 125m
    hostname: client
  server:
    image: punss21/multi-server
    mem_limit: 125m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: punss21/multi-worker
    mem_limit: 125m
    hostname: worker
    environment: 
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: punss21/nginx
    mem_limit: 125m
    hostname: nginx
    ports:
      - "80:80"
